### ISSUE TITLE
Problem with Gromov Wasserstein 

### ISSUE THREAD

**Issue by JoannaGitHub1** [trneedham/Decorated-Merge-Trees#1]
When I try to compile the line:
res = merge_tree_interleaving_distance(MT1,MT2,mesh,verbose = False)
I get the error:
cannot unpack non-iterable numpy.float64 object
I fount out the error is because of Gromov Wasserstein but I found an example where it worked (https://pythonot.github.io/auto_examples/gromov/plot_gromov.html). This does not work on the origin code. Do you have an idea how to fix the issue?

**Comment by trneedham** [comment]
I think the bug should be fixed now. Thanks for bringing this to my attention!
